# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
<<<<<<< HEAD
title:            Lanyon
tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5
=======
title:            Derek Chen
tagline:          ''
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://derektrc.github.io
baseurl:          /
>>>>>>> origin/master

author:
  name:           'Derek Chen'
  url:            https://twitter.com/derektrc

# Custom vars
version:          1.0.0

github:
<<<<<<< HEAD
  repo:           https://github.com/poole/lanyon
=======
  repo:           https://github.com/derektrc
>>>>>>> origin/master
