# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Derek Chen
tagline:          'About'
description:      "<a href='https://www.youtube.com/watch?v=l6svfDWzd-4&t=2s'>Don't you dream impossible things?</a>"
url:              http://derektrc.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Derek Chen'
  url:            https://twitter.com/derektrc

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/derektrc
