# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Derek Chen
tagline:          ''
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://derektrc.github.io
baseurl:          /

author:
  name:           'Derek Chen'
  url:            https://twitter.com/derektrc

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/derektrc
