# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Derek Chen
tagline:          'About'
description:      'Let your life lightly dance on the edges of time like dew on the tip of a leaf. - R. Tagore'
url:              http://derektrc.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Derek Chen'
  url:            https://twitter.com/derektrc

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/derektrc
